//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Schema;

namespace FlighBooking_ThomasZerr.FlightBookingReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="FlightBookingReference.Z_HH_FlightBooking_MT_01")]
    public interface Z_HH_FlightBooking_MT_01 {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightBookingCancel weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse1 FlightBookingCancel(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse1> FlightBookingCancelAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightBookingConfirm weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse1 FlightBookingConfirm(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse1> FlightBookingConfirmAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightBookingCreateFromData weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse1 FlightBookingCreateFromData(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse1> FlightBookingCreateFromDataAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightBookingGetList weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse1 FlightBookingGetList(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse1> FlightBookingGetListAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang BapiServiceTransactionCommit weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse1 BapiServiceTransactionCommit(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse1> BapiServiceTransactionCommitAsync(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang BapiServiceTransactionRollback weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse1 BapiServiceTransactionRollback(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse1> BapiServiceTransactionRollbackAsync(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingCancel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineIDField;
        
        private string bookingNumberField;
        
        private string testRunField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AirlineID {
            get {
                return this.airlineIDField;
            }
            set {
                this.airlineIDField = value;
                this.RaisePropertyChanged("AirlineID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BookingNumber {
            get {
                return this.bookingNumberField;
            }
            set {
                this.bookingNumberField = value;
                this.RaisePropertyChanged("BookingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TestRun {
            get {
                return this.testRunField;
            }
            set {
                this.testRunField = value;
                this.RaisePropertyChanged("TestRun");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisbodat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineidField;
        
        private string bookingidField;
        
        private string connectidField;
        
        private string flightdateField;
        
        private string customeridField;
        
        private string classField;
        
        private string bookdateField;
        
        private string counterField;
        
        private string agencynumField;
        
        private string reservedField;
        
        private string cancelledField;
        
        private string passnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Airlineid {
            get {
                return this.airlineidField;
            }
            set {
                this.airlineidField = value;
                this.RaisePropertyChanged("Airlineid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Bookingid {
            get {
                return this.bookingidField;
            }
            set {
                this.bookingidField = value;
                this.RaisePropertyChanged("Bookingid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Connectid {
            get {
                return this.connectidField;
            }
            set {
                this.connectidField = value;
                this.RaisePropertyChanged("Connectid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Flightdate {
            get {
                return this.flightdateField;
            }
            set {
                this.flightdateField = value;
                this.RaisePropertyChanged("Flightdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Customerid {
            get {
                return this.customeridField;
            }
            set {
                this.customeridField = value;
                this.RaisePropertyChanged("Customerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Bookdate {
            get {
                return this.bookdateField;
            }
            set {
                this.bookdateField = value;
                this.RaisePropertyChanged("Bookdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
                this.RaisePropertyChanged("Counter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Agencynum {
            get {
                return this.agencynumField;
            }
            set {
                this.agencynumField = value;
                this.RaisePropertyChanged("Agencynum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
                this.RaisePropertyChanged("Reserved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
                this.RaisePropertyChanged("Cancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Passname {
            get {
                return this.passnameField;
            }
            set {
                this.passnameField = value;
                this.RaisePropertyChanged("Passname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisfldra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signField;
        
        private string optionField;
        
        private string lowField;
        
        private string highField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("Sign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
                this.RaisePropertyChanged("Option");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
                this.RaisePropertyChanged("Low");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string High {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
                this.RaisePropertyChanged("High");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisbopri : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal priceField;
        
        private decimal taxField;
        
        private string currField;
        
        private string currIsoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
                this.RaisePropertyChanged("Tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Curr {
            get {
                return this.currField;
            }
            set {
                this.currField = value;
                this.RaisePropertyChanged("Curr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CurrIso {
            get {
                return this.currIsoField;
            }
            set {
                this.currIsoField = value;
                this.RaisePropertyChanged("CurrIso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiparex : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string structureField;
        
        private string valuepart1Field;
        
        private string valuepart2Field;
        
        private string valuepart3Field;
        
        private string valuepart4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Structure {
            get {
                return this.structureField;
            }
            set {
                this.structureField = value;
                this.RaisePropertyChanged("Structure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valuepart1 {
            get {
                return this.valuepart1Field;
            }
            set {
                this.valuepart1Field = value;
                this.RaisePropertyChanged("Valuepart1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Valuepart2 {
            get {
                return this.valuepart2Field;
            }
            set {
                this.valuepart2Field = value;
                this.RaisePropertyChanged("Valuepart2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Valuepart3 {
            get {
                return this.valuepart3Field;
            }
            set {
                this.valuepart3Field = value;
                this.RaisePropertyChanged("Valuepart3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Valuepart4 {
            get {
                return this.valuepart4Field;
            }
            set {
                this.valuepart4Field = value;
                this.RaisePropertyChanged("Valuepart4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisbonew : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineidField;
        
        private string connectidField;
        
        private string flightdateField;
        
        private string customeridField;
        
        private string classField;
        
        private string counterField;
        
        private string agencynumField;
        
        private string passnameField;
        
        private string passformField;
        
        private string passbirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Airlineid {
            get {
                return this.airlineidField;
            }
            set {
                this.airlineidField = value;
                this.RaisePropertyChanged("Airlineid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Connectid {
            get {
                return this.connectidField;
            }
            set {
                this.connectidField = value;
                this.RaisePropertyChanged("Connectid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Flightdate {
            get {
                return this.flightdateField;
            }
            set {
                this.flightdateField = value;
                this.RaisePropertyChanged("Flightdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Customerid {
            get {
                return this.customeridField;
            }
            set {
                this.customeridField = value;
                this.RaisePropertyChanged("Customerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Counter {
            get {
                return this.counterField;
            }
            set {
                this.counterField = value;
                this.RaisePropertyChanged("Counter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Agencynum {
            get {
                return this.agencynumField;
            }
            set {
                this.agencynumField = value;
                this.RaisePropertyChanged("Agencynum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Passname {
            get {
                return this.passnameField;
            }
            set {
                this.passnameField = value;
                this.RaisePropertyChanged("Passname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Passform {
            get {
                return this.passformField;
            }
            set {
                this.passformField = value;
                this.RaisePropertyChanged("Passform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Passbirth {
            get {
                return this.passbirthField;
            }
            set {
                this.passbirthField = value;
                this.RaisePropertyChanged("Passbirth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private int rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=4)]
        public string LogNo {
            get {
                return this.logNoField;
            }
            set {
                this.logNoField = value;
                this.RaisePropertyChanged("LogNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=5)]
        public string LogMsgNo {
            get {
                return this.logMsgNoField;
            }
            set {
                this.logMsgNoField = value;
                this.RaisePropertyChanged("LogMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=6)]
        public string MessageV1 {
            get {
                return this.messageV1Field;
            }
            set {
                this.messageV1Field = value;
                this.RaisePropertyChanged("MessageV1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=7)]
        public string MessageV2 {
            get {
                return this.messageV2Field;
            }
            set {
                this.messageV2Field = value;
                this.RaisePropertyChanged("MessageV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=8)]
        public string MessageV3 {
            get {
                return this.messageV3Field;
            }
            set {
                this.messageV3Field = value;
                this.RaisePropertyChanged("MessageV3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=9)]
        public string MessageV4 {
            get {
                return this.messageV4Field;
            }
            set {
                this.messageV4Field = value;
                this.RaisePropertyChanged("MessageV4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=10)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("Parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=11)]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=12)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=13)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("System");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingCancelResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingCancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancel FlightBookingCancel;
        
        public FlightBookingCancelRequest() {
        }
        
        public FlightBookingCancelRequest(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancel FlightBookingCancel) {
            this.FlightBookingCancel = FlightBookingCancel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingCancelResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse FlightBookingCancelResponse;
        
        public FlightBookingCancelResponse1() {
        }
        
        public FlightBookingCancelResponse1(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse FlightBookingCancelResponse) {
            this.FlightBookingCancelResponse = FlightBookingCancelResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingConfirm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineIDField;
        
        private string bookingNumberField;
        
        private string testRunField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AirlineID {
            get {
                return this.airlineIDField;
            }
            set {
                this.airlineIDField = value;
                this.RaisePropertyChanged("AirlineID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BookingNumber {
            get {
                return this.bookingNumberField;
            }
            set {
                this.bookingNumberField = value;
                this.RaisePropertyChanged("BookingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TestRun {
            get {
                return this.testRunField;
            }
            set {
                this.testRunField = value;
                this.RaisePropertyChanged("TestRun");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingConfirmResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingConfirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirm FlightBookingConfirm;
        
        public FlightBookingConfirmRequest() {
        }
        
        public FlightBookingConfirmRequest(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirm FlightBookingConfirm) {
            this.FlightBookingConfirm = FlightBookingConfirm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingConfirmResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse FlightBookingConfirmResponse;
        
        public FlightBookingConfirmResponse1() {
        }
        
        public FlightBookingConfirmResponse1(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse FlightBookingConfirmResponse) {
            this.FlightBookingConfirmResponse = FlightBookingConfirmResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingCreateFromData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapisbonew bookingDataField;
        
        private Bapiparex[] extensionInField;
        
        private string reserveOnlyField;
        
        private string testRunField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Bapisbonew BookingData {
            get {
                return this.bookingDataField;
            }
            set {
                this.bookingDataField = value;
                this.RaisePropertyChanged("BookingData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionIn {
            get {
                return this.extensionInField;
            }
            set {
                this.extensionInField = value;
                this.RaisePropertyChanged("ExtensionIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ReserveOnly {
            get {
                return this.reserveOnlyField;
            }
            set {
                this.reserveOnlyField = value;
                this.RaisePropertyChanged("ReserveOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TestRun {
            get {
                return this.testRunField;
            }
            set {
                this.testRunField = value;
                this.RaisePropertyChanged("TestRun");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingCreateFromDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineIDField;
        
        private string bookingNumberField;
        
        private Bapiret2[] returnField;
        
        private Bapisbopri ticketPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AirlineID {
            get {
                return this.airlineIDField;
            }
            set {
                this.airlineIDField = value;
                this.RaisePropertyChanged("AirlineID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BookingNumber {
            get {
                return this.bookingNumberField;
            }
            set {
                this.bookingNumberField = value;
                this.RaisePropertyChanged("BookingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Bapisbopri TicketPrice {
            get {
                return this.ticketPriceField;
            }
            set {
                this.ticketPriceField = value;
                this.RaisePropertyChanged("TicketPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingCreateFromDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromData FlightBookingCreateFromData;
        
        public FlightBookingCreateFromDataRequest() {
        }
        
        public FlightBookingCreateFromDataRequest(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromData FlightBookingCreateFromData) {
            this.FlightBookingCreateFromData = FlightBookingCreateFromData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingCreateFromDataResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse FlightBookingCreateFromDataResponse;
        
        public FlightBookingCreateFromDataResponse1() {
        }
        
        public FlightBookingCreateFromDataResponse1(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse FlightBookingCreateFromDataResponse) {
            this.FlightBookingCreateFromDataResponse = FlightBookingCreateFromDataResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingGetList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineField;
        
        private Bapisfldra[] bookingDateRangeField;
        
        private string customerNumberField;
        
        private Bapiparex[] extensionInField;
        
        private Bapisfldra[] flightDateRangeField;
        
        private int maxRowsField;
        
        private bool maxRowsFieldSpecified;
        
        private string travelAgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
                this.RaisePropertyChanged("Airline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapisfldra[] BookingDateRange {
            get {
                return this.bookingDateRangeField;
            }
            set {
                this.bookingDateRangeField = value;
                this.RaisePropertyChanged("BookingDateRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionIn {
            get {
                return this.extensionInField;
            }
            set {
                this.extensionInField = value;
                this.RaisePropertyChanged("ExtensionIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapisfldra[] FlightDateRange {
            get {
                return this.flightDateRangeField;
            }
            set {
                this.flightDateRangeField = value;
                this.RaisePropertyChanged("FlightDateRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int MaxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
                this.RaisePropertyChanged("MaxRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxRowsSpecified {
            get {
                return this.maxRowsFieldSpecified;
            }
            set {
                this.maxRowsFieldSpecified = value;
                this.RaisePropertyChanged("MaxRowsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TravelAgency {
            get {
                return this.travelAgencyField;
            }
            set {
                this.travelAgencyField = value;
                this.RaisePropertyChanged("TravelAgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightBookingGetListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapisbodat[] bookingListField;
        
        private Bapiparex[] extensionOutField;
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapisbodat[] BookingList {
            get {
                return this.bookingListField;
            }
            set {
                this.bookingListField = value;
                this.RaisePropertyChanged("BookingList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionOut {
            get {
                return this.extensionOutField;
            }
            set {
                this.extensionOutField = value;
                this.RaisePropertyChanged("ExtensionOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingGetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetList FlightBookingGetList;
        
        public FlightBookingGetListRequest() {
        }
        
        public FlightBookingGetListRequest(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetList FlightBookingGetList) {
            this.FlightBookingGetList = FlightBookingGetList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightBookingGetListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse FlightBookingGetListResponse;
        
        public FlightBookingGetListResponse1() {
        }
        
        public FlightBookingGetListResponse1(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse FlightBookingGetListResponse) {
            this.FlightBookingGetListResponse = FlightBookingGetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionCommit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wAITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WAIT {
            get {
                return this.wAITField;
            }
            set {
                this.wAITField = value;
                this.RaisePropertyChanged("WAIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionCommitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiret2 returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Bapiret2 Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionCommitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommit BapiServiceTransactionCommit;
        
        public BapiServiceTransactionCommitRequest() {
        }
        
        public BapiServiceTransactionCommitRequest(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommit BapiServiceTransactionCommit) {
            this.BapiServiceTransactionCommit = BapiServiceTransactionCommit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionCommitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse BapiServiceTransactionCommitResponse;
        
        public BapiServiceTransactionCommitResponse1() {
        }
        
        public BapiServiceTransactionCommitResponse1(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse BapiServiceTransactionCommitResponse) {
            this.BapiServiceTransactionCommitResponse = BapiServiceTransactionCommitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionRollback : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionRollbackResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiret2 returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Bapiret2 Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionRollbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollback BapiServiceTransactionRollback;
        
        public BapiServiceTransactionRollbackRequest() {
        }
        
        public BapiServiceTransactionRollbackRequest(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollback BapiServiceTransactionRollback) {
            this.BapiServiceTransactionRollback = BapiServiceTransactionRollback;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionRollbackResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse BapiServiceTransactionRollbackResponse;
        
        public BapiServiceTransactionRollbackResponse1() {
        }
        
        public BapiServiceTransactionRollbackResponse1(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse BapiServiceTransactionRollbackResponse) {
            this.BapiServiceTransactionRollbackResponse = BapiServiceTransactionRollbackResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_HH_FlightBooking_MT_01Channel : FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_HH_FlightBooking_MT_01Client : System.ServiceModel.ClientBase<FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01>, FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01 {
        
        public Z_HH_FlightBooking_MT_01Client() {
        }
        
        public Z_HH_FlightBooking_MT_01Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_HH_FlightBooking_MT_01Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_HH_FlightBooking_MT_01Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_HH_FlightBooking_MT_01Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse1 FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingCancel(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest request) {
            return base.Channel.FlightBookingCancel(request);
        }
        
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse FlightBookingCancel(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancel FlightBookingCancel1) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest();
            inValue.FlightBookingCancel = FlightBookingCancel1;
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse1 retVal = ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingCancel(inValue);
            return retVal.FlightBookingCancelResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse1> FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingCancelAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest request) {
            return base.Channel.FlightBookingCancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelResponse1> FlightBookingCancelAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancel FlightBookingCancel) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCancelRequest();
            inValue.FlightBookingCancel = FlightBookingCancel;
            return ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingCancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse1 FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingConfirm(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest request) {
            return base.Channel.FlightBookingConfirm(request);
        }
        
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse FlightBookingConfirm(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirm FlightBookingConfirm1) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest();
            inValue.FlightBookingConfirm = FlightBookingConfirm1;
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse1 retVal = ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingConfirm(inValue);
            return retVal.FlightBookingConfirmResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse1> FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingConfirmAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest request) {
            return base.Channel.FlightBookingConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmResponse1> FlightBookingConfirmAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirm FlightBookingConfirm) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingConfirmRequest();
            inValue.FlightBookingConfirm = FlightBookingConfirm;
            return ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingConfirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse1 FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingCreateFromData(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest request) {
            return base.Channel.FlightBookingCreateFromData(request);
        }
        
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse FlightBookingCreateFromData(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromData FlightBookingCreateFromData1) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest();
            inValue.FlightBookingCreateFromData = FlightBookingCreateFromData1;
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse1 retVal = ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingCreateFromData(inValue);
            return retVal.FlightBookingCreateFromDataResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse1> FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingCreateFromDataAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest request) {
            return base.Channel.FlightBookingCreateFromDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataResponse1> FlightBookingCreateFromDataAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromData FlightBookingCreateFromData) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingCreateFromDataRequest();
            inValue.FlightBookingCreateFromData = FlightBookingCreateFromData;
            return ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingCreateFromDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse1 FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingGetList(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest request) {
            return base.Channel.FlightBookingGetList(request);
        }
        
        public FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse FlightBookingGetList(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetList FlightBookingGetList1) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest();
            inValue.FlightBookingGetList = FlightBookingGetList1;
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse1 retVal = ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingGetList(inValue);
            return retVal.FlightBookingGetListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse1> FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.FlightBookingGetListAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest request) {
            return base.Channel.FlightBookingGetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListResponse1> FlightBookingGetListAsync(FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetList FlightBookingGetList) {
            FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.FlightBookingGetListRequest();
            inValue.FlightBookingGetList = FlightBookingGetList;
            return ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).FlightBookingGetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse1 FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.BapiServiceTransactionCommit(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest request) {
            return base.Channel.BapiServiceTransactionCommit(request);
        }
        
        public FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse BapiServiceTransactionCommit(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommit BapiServiceTransactionCommit1) {
            FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest();
            inValue.BapiServiceTransactionCommit = BapiServiceTransactionCommit1;
            FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse1 retVal = ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).BapiServiceTransactionCommit(inValue);
            return retVal.BapiServiceTransactionCommitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse1> FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.BapiServiceTransactionCommitAsync(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest request) {
            return base.Channel.BapiServiceTransactionCommitAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitResponse1> BapiServiceTransactionCommitAsync(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommit BapiServiceTransactionCommit) {
            FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionCommitRequest();
            inValue.BapiServiceTransactionCommit = BapiServiceTransactionCommit;
            return ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).BapiServiceTransactionCommitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse1 FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.BapiServiceTransactionRollback(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest request) {
            return base.Channel.BapiServiceTransactionRollback(request);
        }
        
        public FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse BapiServiceTransactionRollback(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollback BapiServiceTransactionRollback1) {
            FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest();
            inValue.BapiServiceTransactionRollback = BapiServiceTransactionRollback1;
            FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse1 retVal = ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).BapiServiceTransactionRollback(inValue);
            return retVal.BapiServiceTransactionRollbackResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse1> FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01.BapiServiceTransactionRollbackAsync(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest request) {
            return base.Channel.BapiServiceTransactionRollbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackResponse1> BapiServiceTransactionRollbackAsync(FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollback BapiServiceTransactionRollback) {
            FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest inValue = new FlighBooking_ThomasZerr.FlightBookingReference.BapiServiceTransactionRollbackRequest();
            inValue.BapiServiceTransactionRollback = BapiServiceTransactionRollback;
            return ((FlighBooking_ThomasZerr.FlightBookingReference.Z_HH_FlightBooking_MT_01)(this)).BapiServiceTransactionRollbackAsync(inValue);
        }
    }
}
