//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Schema;

namespace FlighBooking_ThomasZerr.Flight {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="Flight.Z_FLIGHT_MT")]
    public interface Z_FLIGHT_MT {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightCheckAvailibility weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse1 FlightCheckAvailibility(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse1> FlightCheckAvailibilityAsync(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightGetDetail weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse1 FlightGetDetail(FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse1> FlightGetDetailAsync(FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightGetList weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.Flight.FlightGetListResponse1 FlightGetList(FlighBooking_ThomasZerr.Flight.FlightGetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightGetListResponse1> FlightGetListAsync(FlighBooking_ThomasZerr.Flight.FlightGetListRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang FlightSaveReplica weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse1 FlightSaveReplica(FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse1> FlightSaveReplicaAsync(FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang BapiServiceTransactionCommit weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse1 BapiServiceTransactionCommit(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse1> BapiServiceTransactionCommitAsync(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang BapiServiceTransactionRollback weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse1 BapiServiceTransactionRollback(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse1> BapiServiceTransactionRollbackAsync(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightCheckAvailibility : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineIDField;
        
        private string connectionIDField;
        
        private string flightDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AirlineID {
            get {
                return this.airlineIDField;
            }
            set {
                this.airlineIDField = value;
                this.RaisePropertyChanged("AirlineID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConnectionID {
            get {
                return this.connectionIDField;
            }
            set {
                this.connectionIDField = value;
                this.RaisePropertyChanged("ConnectionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FlightDate {
            get {
                return this.flightDateField;
            }
            set {
                this.flightDateField = value;
                this.RaisePropertyChanged("FlightDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisflrep : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineidField;
        
        private string connectidField;
        
        private string flightdateField;
        
        private decimal priceField;
        
        private string currField;
        
        private string currIsoField;
        
        private string planetypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Airlineid {
            get {
                return this.airlineidField;
            }
            set {
                this.airlineidField = value;
                this.RaisePropertyChanged("Airlineid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Connectid {
            get {
                return this.connectidField;
            }
            set {
                this.connectidField = value;
                this.RaisePropertyChanged("Connectid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Flightdate {
            get {
                return this.flightdateField;
            }
            set {
                this.flightdateField = value;
                this.RaisePropertyChanged("Flightdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Curr {
            get {
                return this.currField;
            }
            set {
                this.currField = value;
                this.RaisePropertyChanged("Curr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CurrIso {
            get {
                return this.currIsoField;
            }
            set {
                this.currIsoField = value;
                this.RaisePropertyChanged("CurrIso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Planetype {
            get {
                return this.planetypeField;
            }
            set {
                this.planetypeField = value;
                this.RaisePropertyChanged("Planetype");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisfldst : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airportidField;
        
        private string cityField;
        
        private string countrField;
        
        private string countrIsoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Airportid {
            get {
                return this.airportidField;
            }
            set {
                this.airportidField = value;
                this.RaisePropertyChanged("Airportid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Countr {
            get {
                return this.countrField;
            }
            set {
                this.countrField = value;
                this.RaisePropertyChanged("Countr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CountrIso {
            get {
                return this.countrIsoField;
            }
            set {
                this.countrIsoField = value;
                this.RaisePropertyChanged("CountrIso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisfldra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signField;
        
        private string optionField;
        
        private string lowField;
        
        private string highField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("Sign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
                this.RaisePropertyChanged("Option");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
                this.RaisePropertyChanged("Low");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string High {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
                this.RaisePropertyChanged("High");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisfldat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineidField;
        
        private string airlineField;
        
        private string connectidField;
        
        private string flightdateField;
        
        private string airportfrField;
        
        private string cityfromField;
        
        private string airporttoField;
        
        private string citytoField;
        
        private string deptimeField;
        
        private string arrtimeField;
        
        private string arrdateField;
        
        private decimal priceField;
        
        private string currField;
        
        private string currIsoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Airlineid {
            get {
                return this.airlineidField;
            }
            set {
                this.airlineidField = value;
                this.RaisePropertyChanged("Airlineid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
                this.RaisePropertyChanged("Airline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Connectid {
            get {
                return this.connectidField;
            }
            set {
                this.connectidField = value;
                this.RaisePropertyChanged("Connectid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Flightdate {
            get {
                return this.flightdateField;
            }
            set {
                this.flightdateField = value;
                this.RaisePropertyChanged("Flightdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Airportfr {
            get {
                return this.airportfrField;
            }
            set {
                this.airportfrField = value;
                this.RaisePropertyChanged("Airportfr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Cityfrom {
            get {
                return this.cityfromField;
            }
            set {
                this.cityfromField = value;
                this.RaisePropertyChanged("Cityfrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Airportto {
            get {
                return this.airporttoField;
            }
            set {
                this.airporttoField = value;
                this.RaisePropertyChanged("Airportto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Cityto {
            get {
                return this.citytoField;
            }
            set {
                this.citytoField = value;
                this.RaisePropertyChanged("Cityto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Deptime {
            get {
                return this.deptimeField;
            }
            set {
                this.deptimeField = value;
                this.RaisePropertyChanged("Deptime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Arrtime {
            get {
                return this.arrtimeField;
            }
            set {
                this.arrtimeField = value;
                this.RaisePropertyChanged("Arrtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Arrdate {
            get {
                return this.arrdateField;
            }
            set {
                this.arrdateField = value;
                this.RaisePropertyChanged("Arrdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Curr {
            get {
                return this.currField;
            }
            set {
                this.currField = value;
                this.RaisePropertyChanged("Curr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CurrIso {
            get {
                return this.currIsoField;
            }
            set {
                this.currIsoField = value;
                this.RaisePropertyChanged("CurrIso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisfladd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int flighttimeField;
        
        private decimal distanceField;
        
        private string unitField;
        
        private string unitIsoField;
        
        private string planetypeField;
        
        private string flighttypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Flighttime {
            get {
                return this.flighttimeField;
            }
            set {
                this.flighttimeField = value;
                this.RaisePropertyChanged("Flighttime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UnitIso {
            get {
                return this.unitIsoField;
            }
            set {
                this.unitIsoField = value;
                this.RaisePropertyChanged("UnitIso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Planetype {
            get {
                return this.planetypeField;
            }
            set {
                this.planetypeField = value;
                this.RaisePropertyChanged("Planetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Flighttype {
            get {
                return this.flighttypeField;
            }
            set {
                this.flighttypeField = value;
                this.RaisePropertyChanged("Flighttype");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiparex : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string structureField;
        
        private string valuepart1Field;
        
        private string valuepart2Field;
        
        private string valuepart3Field;
        
        private string valuepart4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Structure {
            get {
                return this.structureField;
            }
            set {
                this.structureField = value;
                this.RaisePropertyChanged("Structure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valuepart1 {
            get {
                return this.valuepart1Field;
            }
            set {
                this.valuepart1Field = value;
                this.RaisePropertyChanged("Valuepart1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Valuepart2 {
            get {
                return this.valuepart2Field;
            }
            set {
                this.valuepart2Field = value;
                this.RaisePropertyChanged("Valuepart2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Valuepart3 {
            get {
                return this.valuepart3Field;
            }
            set {
                this.valuepart3Field = value;
                this.RaisePropertyChanged("Valuepart3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Valuepart4 {
            get {
                return this.valuepart4Field;
            }
            set {
                this.valuepart4Field = value;
                this.RaisePropertyChanged("Valuepart4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private int rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=4)]
        public string LogNo {
            get {
                return this.logNoField;
            }
            set {
                this.logNoField = value;
                this.RaisePropertyChanged("LogNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=5)]
        public string LogMsgNo {
            get {
                return this.logMsgNoField;
            }
            set {
                this.logMsgNoField = value;
                this.RaisePropertyChanged("LogMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=6)]
        public string MessageV1 {
            get {
                return this.messageV1Field;
            }
            set {
                this.messageV1Field = value;
                this.RaisePropertyChanged("MessageV1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=7)]
        public string MessageV2 {
            get {
                return this.messageV2Field;
            }
            set {
                this.messageV2Field = value;
                this.RaisePropertyChanged("MessageV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=8)]
        public string MessageV3 {
            get {
                return this.messageV3Field;
            }
            set {
                this.messageV3Field = value;
                this.RaisePropertyChanged("MessageV3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=9)]
        public string MessageV4 {
            get {
                return this.messageV4Field;
            }
            set {
                this.messageV4Field = value;
                this.RaisePropertyChanged("MessageV4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=10)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("Parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=11)]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=12)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=13)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("System");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapisflava : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int economaxField;
        
        private int econofreeField;
        
        private int businmaxField;
        
        private int businfreeField;
        
        private int firstmaxField;
        
        private int firstfreeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Economax {
            get {
                return this.economaxField;
            }
            set {
                this.economaxField = value;
                this.RaisePropertyChanged("Economax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Econofree {
            get {
                return this.econofreeField;
            }
            set {
                this.econofreeField = value;
                this.RaisePropertyChanged("Econofree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Businmax {
            get {
                return this.businmaxField;
            }
            set {
                this.businmaxField = value;
                this.RaisePropertyChanged("Businmax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int Businfree {
            get {
                return this.businfreeField;
            }
            set {
                this.businfreeField = value;
                this.RaisePropertyChanged("Businfree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int Firstmax {
            get {
                return this.firstmaxField;
            }
            set {
                this.firstmaxField = value;
                this.RaisePropertyChanged("Firstmax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int Firstfree {
            get {
                return this.firstfreeField;
            }
            set {
                this.firstfreeField = value;
                this.RaisePropertyChanged("Firstfree");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightCheckAvailibilityResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapisflava availibilityField;
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Bapisflava Availibility {
            get {
                return this.availibilityField;
            }
            set {
                this.availibilityField = value;
                this.RaisePropertyChanged("Availibility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightCheckAvailibilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightCheckAvailibility FlightCheckAvailibility;
        
        public FlightCheckAvailibilityRequest() {
        }
        
        public FlightCheckAvailibilityRequest(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibility FlightCheckAvailibility) {
            this.FlightCheckAvailibility = FlightCheckAvailibility;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightCheckAvailibilityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse FlightCheckAvailibilityResponse;
        
        public FlightCheckAvailibilityResponse1() {
        }
        
        public FlightCheckAvailibilityResponse1(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse FlightCheckAvailibilityResponse) {
            this.FlightCheckAvailibilityResponse = FlightCheckAvailibilityResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightGetDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineIDField;
        
        private string connectionIDField;
        
        private Bapiparex[] extensionInField;
        
        private string flightDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AirlineID {
            get {
                return this.airlineIDField;
            }
            set {
                this.airlineIDField = value;
                this.RaisePropertyChanged("AirlineID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ConnectionID {
            get {
                return this.connectionIDField;
            }
            set {
                this.connectionIDField = value;
                this.RaisePropertyChanged("ConnectionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionIn {
            get {
                return this.extensionInField;
            }
            set {
                this.extensionInField = value;
                this.RaisePropertyChanged("ExtensionIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FlightDate {
            get {
                return this.flightDateField;
            }
            set {
                this.flightDateField = value;
                this.RaisePropertyChanged("FlightDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightGetDetailResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapisfladd additionalInfoField;
        
        private Bapisflava availibilityField;
        
        private Bapiparex[] extensionOutField;
        
        private Bapisfldat flightDataField;
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Bapisfladd AdditionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("AdditionalInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Bapisflava Availibility {
            get {
                return this.availibilityField;
            }
            set {
                this.availibilityField = value;
                this.RaisePropertyChanged("Availibility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionOut {
            get {
                return this.extensionOutField;
            }
            set {
                this.extensionOutField = value;
                this.RaisePropertyChanged("ExtensionOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Bapisfldat FlightData {
            get {
                return this.flightDataField;
            }
            set {
                this.flightDataField = value;
                this.RaisePropertyChanged("FlightData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightGetDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightGetDetail FlightGetDetail;
        
        public FlightGetDetailRequest() {
        }
        
        public FlightGetDetailRequest(FlighBooking_ThomasZerr.Flight.FlightGetDetail FlightGetDetail) {
            this.FlightGetDetail = FlightGetDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightGetDetailResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse FlightGetDetailResponse;
        
        public FlightGetDetailResponse1() {
        }
        
        public FlightGetDetailResponse1(FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse FlightGetDetailResponse) {
            this.FlightGetDetailResponse = FlightGetDetailResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightGetList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineField;
        
        private Bapisfldra[] dateRangeField;
        
        private Bapisfldst destinationFromField;
        
        private Bapisfldst destinationToField;
        
        private Bapiparex[] extensionInField;
        
        private int maxRowsField;
        
        private bool maxRowsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
                this.RaisePropertyChanged("Airline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapisfldra[] DateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
                this.RaisePropertyChanged("DateRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Bapisfldst DestinationFrom {
            get {
                return this.destinationFromField;
            }
            set {
                this.destinationFromField = value;
                this.RaisePropertyChanged("DestinationFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Bapisfldst DestinationTo {
            get {
                return this.destinationToField;
            }
            set {
                this.destinationToField = value;
                this.RaisePropertyChanged("DestinationTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionIn {
            get {
                return this.extensionInField;
            }
            set {
                this.extensionInField = value;
                this.RaisePropertyChanged("ExtensionIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int MaxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
                this.RaisePropertyChanged("MaxRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxRowsSpecified {
            get {
                return this.maxRowsFieldSpecified;
            }
            set {
                this.maxRowsFieldSpecified = value;
                this.RaisePropertyChanged("MaxRowsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightGetListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiparex[] extensionOutField;
        
        private Bapisfldat[] flightListField;
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionOut {
            get {
                return this.extensionOutField;
            }
            set {
                this.extensionOutField = value;
                this.RaisePropertyChanged("ExtensionOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapisfldat[] FlightList {
            get {
                return this.flightListField;
            }
            set {
                this.flightListField = value;
                this.RaisePropertyChanged("FlightList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightGetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightGetList FlightGetList;
        
        public FlightGetListRequest() {
        }
        
        public FlightGetListRequest(FlighBooking_ThomasZerr.Flight.FlightGetList FlightGetList) {
            this.FlightGetList = FlightGetList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightGetListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightGetListResponse FlightGetListResponse;
        
        public FlightGetListResponse1() {
        }
        
        public FlightGetListResponse1(FlighBooking_ThomasZerr.Flight.FlightGetListResponse FlightGetListResponse) {
            this.FlightGetListResponse = FlightGetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightSaveReplica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiparex[] extensionInField;
        
        private Bapisflrep flightDataField;
        
        private string testRunField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiparex[] ExtensionIn {
            get {
                return this.extensionInField;
            }
            set {
                this.extensionInField = value;
                this.RaisePropertyChanged("ExtensionIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Bapisflrep FlightData {
            get {
                return this.flightDataField;
            }
            set {
                this.flightDataField = value;
                this.RaisePropertyChanged("FlightData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TestRun {
            get {
                return this.testRunField;
            }
            set {
                this.testRunField = value;
                this.RaisePropertyChanged("TestRun");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class FlightSaveReplicaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightSaveReplicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightSaveReplica FlightSaveReplica;
        
        public FlightSaveReplicaRequest() {
        }
        
        public FlightSaveReplicaRequest(FlighBooking_ThomasZerr.Flight.FlightSaveReplica FlightSaveReplica) {
            this.FlightSaveReplica = FlightSaveReplica;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightSaveReplicaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse FlightSaveReplicaResponse;
        
        public FlightSaveReplicaResponse1() {
        }
        
        public FlightSaveReplicaResponse1(FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse FlightSaveReplicaResponse) {
            this.FlightSaveReplicaResponse = FlightSaveReplicaResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionCommit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wAITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WAIT {
            get {
                return this.wAITField;
            }
            set {
                this.wAITField = value;
                this.RaisePropertyChanged("WAIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionCommitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiret2 returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Bapiret2 Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionCommitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommit BapiServiceTransactionCommit;
        
        public BapiServiceTransactionCommitRequest() {
        }
        
        public BapiServiceTransactionCommitRequest(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommit BapiServiceTransactionCommit) {
            this.BapiServiceTransactionCommit = BapiServiceTransactionCommit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionCommitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse BapiServiceTransactionCommitResponse;
        
        public BapiServiceTransactionCommitResponse1() {
        }
        
        public BapiServiceTransactionCommitResponse1(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse BapiServiceTransactionCommitResponse) {
            this.BapiServiceTransactionCommitResponse = BapiServiceTransactionCommitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionRollback : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class BapiServiceTransactionRollbackResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Bapiret2 returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Bapiret2 Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionRollbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollback BapiServiceTransactionRollback;
        
        public BapiServiceTransactionRollbackRequest() {
        }
        
        public BapiServiceTransactionRollbackRequest(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollback BapiServiceTransactionRollback) {
            this.BapiServiceTransactionRollback = BapiServiceTransactionRollback;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BapiServiceTransactionRollbackResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse BapiServiceTransactionRollbackResponse;
        
        public BapiServiceTransactionRollbackResponse1() {
        }
        
        public BapiServiceTransactionRollbackResponse1(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse BapiServiceTransactionRollbackResponse) {
            this.BapiServiceTransactionRollbackResponse = BapiServiceTransactionRollbackResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_FLIGHT_MTChannel : FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_FLIGHT_MTClient : System.ServiceModel.ClientBase<FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT>, FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT {
        
        public Z_FLIGHT_MTClient() {
        }
        
        public Z_FLIGHT_MTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_FLIGHT_MTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_FLIGHT_MTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_FLIGHT_MTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse1 FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightCheckAvailibility(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest request) {
            return base.Channel.FlightCheckAvailibility(request);
        }
        
        public FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse FlightCheckAvailibility(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibility FlightCheckAvailibility1) {
            FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest();
            inValue.FlightCheckAvailibility = FlightCheckAvailibility1;
            FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse1 retVal = ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightCheckAvailibility(inValue);
            return retVal.FlightCheckAvailibilityResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse1> FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightCheckAvailibilityAsync(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest request) {
            return base.Channel.FlightCheckAvailibilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityResponse1> FlightCheckAvailibilityAsync(FlighBooking_ThomasZerr.Flight.FlightCheckAvailibility FlightCheckAvailibility) {
            FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightCheckAvailibilityRequest();
            inValue.FlightCheckAvailibility = FlightCheckAvailibility;
            return ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightCheckAvailibilityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse1 FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightGetDetail(FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest request) {
            return base.Channel.FlightGetDetail(request);
        }
        
        public FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse FlightGetDetail(FlighBooking_ThomasZerr.Flight.FlightGetDetail FlightGetDetail1) {
            FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest();
            inValue.FlightGetDetail = FlightGetDetail1;
            FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse1 retVal = ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightGetDetail(inValue);
            return retVal.FlightGetDetailResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse1> FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightGetDetailAsync(FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest request) {
            return base.Channel.FlightGetDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightGetDetailResponse1> FlightGetDetailAsync(FlighBooking_ThomasZerr.Flight.FlightGetDetail FlightGetDetail) {
            FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightGetDetailRequest();
            inValue.FlightGetDetail = FlightGetDetail;
            return ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightGetDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.Flight.FlightGetListResponse1 FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightGetList(FlighBooking_ThomasZerr.Flight.FlightGetListRequest request) {
            return base.Channel.FlightGetList(request);
        }
        
        public FlighBooking_ThomasZerr.Flight.FlightGetListResponse FlightGetList(FlighBooking_ThomasZerr.Flight.FlightGetList FlightGetList1) {
            FlighBooking_ThomasZerr.Flight.FlightGetListRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightGetListRequest();
            inValue.FlightGetList = FlightGetList1;
            FlighBooking_ThomasZerr.Flight.FlightGetListResponse1 retVal = ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightGetList(inValue);
            return retVal.FlightGetListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightGetListResponse1> FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightGetListAsync(FlighBooking_ThomasZerr.Flight.FlightGetListRequest request) {
            return base.Channel.FlightGetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightGetListResponse1> FlightGetListAsync(FlighBooking_ThomasZerr.Flight.FlightGetList FlightGetList) {
            FlighBooking_ThomasZerr.Flight.FlightGetListRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightGetListRequest();
            inValue.FlightGetList = FlightGetList;
            return ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightGetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse1 FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightSaveReplica(FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest request) {
            return base.Channel.FlightSaveReplica(request);
        }
        
        public FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse FlightSaveReplica(FlighBooking_ThomasZerr.Flight.FlightSaveReplica FlightSaveReplica1) {
            FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest();
            inValue.FlightSaveReplica = FlightSaveReplica1;
            FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse1 retVal = ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightSaveReplica(inValue);
            return retVal.FlightSaveReplicaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse1> FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.FlightSaveReplicaAsync(FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest request) {
            return base.Channel.FlightSaveReplicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.FlightSaveReplicaResponse1> FlightSaveReplicaAsync(FlighBooking_ThomasZerr.Flight.FlightSaveReplica FlightSaveReplica) {
            FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest inValue = new FlighBooking_ThomasZerr.Flight.FlightSaveReplicaRequest();
            inValue.FlightSaveReplica = FlightSaveReplica;
            return ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).FlightSaveReplicaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse1 FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.BapiServiceTransactionCommit(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest request) {
            return base.Channel.BapiServiceTransactionCommit(request);
        }
        
        public FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse BapiServiceTransactionCommit(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommit BapiServiceTransactionCommit1) {
            FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest inValue = new FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest();
            inValue.BapiServiceTransactionCommit = BapiServiceTransactionCommit1;
            FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse1 retVal = ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).BapiServiceTransactionCommit(inValue);
            return retVal.BapiServiceTransactionCommitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse1> FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.BapiServiceTransactionCommitAsync(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest request) {
            return base.Channel.BapiServiceTransactionCommitAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitResponse1> BapiServiceTransactionCommitAsync(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommit BapiServiceTransactionCommit) {
            FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest inValue = new FlighBooking_ThomasZerr.Flight.BapiServiceTransactionCommitRequest();
            inValue.BapiServiceTransactionCommit = BapiServiceTransactionCommit;
            return ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).BapiServiceTransactionCommitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse1 FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.BapiServiceTransactionRollback(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest request) {
            return base.Channel.BapiServiceTransactionRollback(request);
        }
        
        public FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse BapiServiceTransactionRollback(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollback BapiServiceTransactionRollback1) {
            FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest inValue = new FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest();
            inValue.BapiServiceTransactionRollback = BapiServiceTransactionRollback1;
            FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse1 retVal = ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).BapiServiceTransactionRollback(inValue);
            return retVal.BapiServiceTransactionRollbackResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse1> FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT.BapiServiceTransactionRollbackAsync(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest request) {
            return base.Channel.BapiServiceTransactionRollbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackResponse1> BapiServiceTransactionRollbackAsync(FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollback BapiServiceTransactionRollback) {
            FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest inValue = new FlighBooking_ThomasZerr.Flight.BapiServiceTransactionRollbackRequest();
            inValue.BapiServiceTransactionRollback = BapiServiceTransactionRollback;
            return ((FlighBooking_ThomasZerr.Flight.Z_FLIGHT_MT)(this)).BapiServiceTransactionRollbackAsync(inValue);
        }
    }
}
